### ISSUE TITLE
Phase 0 Beacon Chain Implementation Tracking

### ISSUE THREAD

**Issue by tersec** [status-im/nimbus-eth2#1864]
The list is automatically generated from https://raw.githubusercontent.com/ethereum/eth2.0-specs/v1.0.0-rc.0/specs/phase0/beacon-chain.md

- [x] Misc
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L155
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L22-L24
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L35-L44
- [x] Gwei values
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L52
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L56
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L59
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L63
- [x] Initial values
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/presets.nim#L129
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L68
- [x] Time parameters
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/presets.nim#L130
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L73
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L159
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L76
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L88
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L94-L97
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L111
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L100-L109
- [x] State list lengths
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L118
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L121
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L124
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L127
- [x] Rewards and penalties
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L131-L136
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L46
- [x] Max operations per block
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L140-L145
- [x] Domain types
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L81-L82
- [x] `Fork`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L378-L379
- [x] `ForkData`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L143-L144
- [x] `Checkpoint`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L148-L149
- [x] `Validator`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L341-L342
- [x] `AttestationData`
https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L153-L154
- [x] `IndexedAttestation`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L115-L116
- [x] `PendingAttestation`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L363-L364
- [x] `Eth1Data`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L388-L389
- [x] `HistoricalBatch`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L373-L374
- [x] `DepositMessage`
https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L175-L176
- [x] `DepositData`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L181-L182
- [x] `BeaconBlockHeader`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L239-L240
- [x] `SigningData`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L247-L248
- [x] `ProposerSlashing`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L105-L106
- [x] `AttesterSlashing`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L110-L111
- [x] `Attestation`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L130-L131
- [x] `Deposit`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L168-L169
- [x] `VoluntaryExit`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L190-L191
- [x] `BeaconBlockBody`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L254-L255
- [x] `BeaconBlock`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L197-L198
- [x] `BeaconState`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L285-L286
- [x] `SignedVoluntaryExit`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L401-L402
- [x] `SignedBeaconBlock`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L406-L407
- [x] `SignedBeaconBlockHeader`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L419-L420
- [x] `integer_squareroot`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L25-L26
- [x] `uint_to_bytes`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/helpers.nim#L89-92
- [x] `bytes_to_uint64`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L84
- [x] Crypto
- [x] `hash`
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/digest.nim#L56
- [x] `hash_tree_root`
  https://github.com/status-im/nimbus-eth2/blob/dba39c54d9bb3ded5f624ce026345c3a72f658dd/beacon_chain/ssz/merkleization.nim#L444
- [x] BLS Signatures
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/crypto.nim#L135-L136
- [x] `is_active_validator`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L54-L55
- [x] `is_eligible_for_activation_queue`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L349-L350
- [x] `is_eligible_for_activation`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L355-L356
- [x] `is_slashable_validator`
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L129-L130
- [x] `is_slashable_attestation_data`
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L190-L191
- [x] `is_valid_indexed_attestation`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/block_pools/spec_cache.nim#L85-L86
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L424-L425
- [x] `is_valid_merkle_branch`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L17-L18
- [x] Misc
- [x] `compute_shuffled_index`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/validator.nim#L257-L258
- [x] `compute_proposer_index`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/validator.nim#L295-L296
- [x] `compute_committee`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/validator.nim#L203
- [x] `compute_epoch_at_slot`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L38-L39
- [x] `compute_start_slot_at_epoch`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L49-L50
- [x] `compute_activation_exit_epoch`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L124-L125
- [x] `compute_fork_data_root`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L106-L107
- [x] `compute_fork_digest`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L118-L119
- [x] `compute_domain`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L129-L130
- [x] `compute_signing_root`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L158-L159
- [x] `get_current_epoch`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L72-L73
- [x] `get_previous_epoch`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/validator.nim#L180-L181
- [x] `get_block_root`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L335-L336
- [x] `get_block_root_at_slot`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L322-L323
- [x] `get_randao_mix`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L78-L79
- [x] `get_active_validator_indices`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L59-60
- [x] `get_validator_churn_limit`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L130-L131
- [x] `get_seed`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L168-L169
- [x] `get_committee_count_per_slot`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/block_pools/spec_cache.nim#L20-L21
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/validator.nim#L153-L154
- [x] `get_beacon_committee`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/block_pools/spec_cache.nim#L24-L25
- [x] `get_beacon_proposer_index`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/validator.nim#L322-L323
- [x] `get_total_balance`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L340-L341
- [x] `get_total_active_balance`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L56-L57
- [x] `get_domain`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/helpers.nim#L140-L141
- [x] `get_indexed_attestation`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/block_pools/spec_cache.nim#L46-L47
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L493-L494
- [x] `get_attesting_indices`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/block_pools/spec_cache.nim#L37-L38
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L463-L464
- [x] Beacon state mutators
- [x] `increase_balance`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L37
- [x] `decrease_balance`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L43-L44
- [x] `initiate_validator_exit`
 https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L138-L139
- [x] `slash_validator`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L167-L168
- [x] Genesis state
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L297
- [x] Genesis block
- [x] Epoch processing
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L496-L497
- [x] Helper functions
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L67-L68
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L76
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L83
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_helpers.nim#L30-L31
  `get_attesting_balance` is passed around as a paramater to avoid O(n^2) recalculation.
- [x] Justification and finalization
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L101-L102
- [x] Rewards and penalties
- [x] Helpers
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L246-L247
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L255
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L261
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L264
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L267
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L275
- [x] Components of attestation deltas
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L305-L307
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L317
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L327
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L336
https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L377
- [x] `get_attestation_deltas`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L401-L402
- [x] `process_rewards_and_penalties`
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L416-L417
- [x] Registry updates
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L365-L366
- [x] Slashings
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L433-L434
- [x] Final updates
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/state_transition_epoch.nim#L450-L451
- [x] Block processing
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L352-L353
- [x] Block header
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L41-L42
- [x] RANDAO
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L84-L85
- [x] Eth1 data
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L121-L122
- [x] Operations
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L318-L319
- [x] Proposer slashings
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L136-L137
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L178-L179
- [x] Attester slashings
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L202-L203
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L236-L237
- [x] Attestations
 https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L568-L569
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L604
- [x] Deposits
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L54-L55
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L72
- [x] Voluntary exits
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L254-L255
https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/state_transition_block.nim#L307-L308

**Comment by tersec** [comment]
Everything in https://raw.githubusercontent.com/ethereum/eth2.0-specs/v1.0.0-rc.0/specs/phase0/beacon-chain.md has been implemented and is, to varying degrees, tested by the official EF test suite.
