### ISSUE TITLE
Phase 0 Validator Implementation Tracking

### ISSUE THREAD

**Issue by tersec** [status-im/nimbus-eth2#1865]
Automatically generated from https://raw.githubusercontent.com/ethereum/eth2.0-specs/v1.0.0-rc.0/specs/phase0/validator.md.

Missing required items:
- In "Attesting", "A validator should create and broadcast the `attestation` to the associated attestation subnet when either (a) the validator has received a valid block from the expected block proposer for the assigned `slot` or (b) one-third of the `slot` has transpired (`SECONDS_PER_SLOT / 3` seconds after the start of `slot`) -- whichever comes _first_."  Specifically, the "whichever comes _first_" portion. https://github.com/status-im/nimbus-eth2/issues/1700 tracks this.

- An updated, or at least verified-to-be-current, version of `get_eth1_vote()`. https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/mainchain_monitor.nim#L421-L422 is from v0.11.1 still.

Some optional-for-now (not blocking this issue), but remaining items to track separately:
- "To maximize profit, the validator should attempt to gather aggregate attestations that include singular attestations from the largest number of validators whose signatures from the same epoch have not previously been added on chain."

- https://github.com/ethereum/eth2.0-specs/blob/v1.0.0-rc.0/specs/phase0/validator.md#deposits -- there this would presumably involve getting deposits from mainchain monitor. They don't come from the Eth2 beacon chain itself.

- https://github.com/ethereum/eth2.0-specs/blob/v1.0.0-rc.0/specs/phase0/validator.md#submit-deposit

- We don't initiate slashing ourself, either attester or proposer.

- [x] Constants
- [x] Misc
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/presets/v0_12_3/mainnet.nim#L156-L158
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/network.nim#L22-L23
- [x] BLS public key
- [x] BLS withdrawal key
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/keystore.nim#L715-L719
- [x] Validator index
- [x] Validator assignments
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/validator.nim#L359-L360
- [x] Lookahead
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/network.nim#L125
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/beacon_node.nim#L339
- [x] Block proposal
- [x] Slot
  https://github.com/status-im/nimbus-eth2/blob/513ba72b9a0439bf4bab61b49d7bc7c9f1a1d797/beacon_chain/spec/state_transition.nim#L278-L279
- [x] Proposer index
  https://github.com/status-im/nimbus-eth2/blob/513ba72b9a0439bf4bab61b49d7bc7c9f1a1d797/beacon_chain/spec/state_transition.nim#L278-L280
- [x] Parent root
  https://github.com/status-im/nimbus-eth2/blob/513ba72b9a0439bf4bab61b49d7bc7c9f1a1d797/beacon_chain/spec/state_transition.nim#L278-L281
- [x] Randao reveal
  https://github.com/status-im/nimbus-eth2/blob/3b5a5536e1652bf39065587347147da1bf44b8fb/beacon_chain/validator_duties.nim#L230-L235
- [x] `Eth1Block`
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/mainchain_monitor.nim#L37
- [x] `get_eth1_data`
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/mainchain_monitor.nim#L107-L112
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/mainchain_monitor.nim#L117-L118
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/mainchain_monitor.nim#L421-L422
- [x] Proposer slashings
  https://github.com/status-im/nimbus-eth2/blob/513ba72b9a0439bf4bab61b49d7bc7c9f1a1d797/beacon_chain/exit_pool.nim#L130-L134
- [x] Attester slashings
  https://github.com/status-im/nimbus-eth2/blob/513ba72b9a0439bf4bab61b49d7bc7c9f1a1d797/beacon_chain/exit_pool.nim#L124-L128
- [x] Attestations
  https://github.com/status-im/nimbus-eth2/blob/dba39c54d9bb3ded5f624ce026345c3a72f658dd/beacon_chain/attestation_pool.nim#L298-L301
- [ ] Deposits
- [x] Voluntary exits
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/exit_pool.nim#L66-L70
- [x] State root
  https://github.com/status-im/nimbus-eth2/blob/3b5a5536e1652bf39065587347147da1bf44b8fb/beacon_chain/spec/state_transition.nim#L302-L303
- [x] Signature
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/signatures.nim#L79-L80
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/validator_pool.nim#L58-L59
- [ ] Attesting
- [x] Attestation data
- [x] General
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L662-L665
- [x] LMD GHOST vote
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/block_pools/spec_cache.nim#L166-L170
https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/beaconstate.nim#L662-L666
- [ ] FFG vote
- [x] Data
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/validator_pool.nim#L86
- [x] Aggregation bits
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/validator_pool.nim#L83-L86
- [x] Aggregate signature
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/spec/signatures.nim#L137-L143
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/validator_pool.nim#L69-L70
- [x] Broadcast attestation
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/network.nim#L66-L67
  https://github.com/status-im/nimbus-eth2/blob/513ba72b9a0439bf4bab61b49d7bc7c9f1a1d797/beacon_chain/validator_duties.nim#L136-L140
- [x] Attestation aggregation
- [x] Aggregation selection
  https://github.com/status-im/nimbus-eth2/blob/3b5a5536e1652bf39065587347147da1bf44b8fb/beacon_chain/attestation_aggregation.nim#L25-L36
  https://github.com/status-im/nimbus-eth2/blob/6cf7e837ceb6cfb764b3d95a71fc3b31e2c7a2d3/beacon_chain/spec/signatures.nim#L29-L33
- [x] Construct aggregate
  https://github.com/status-im/nimbus-eth2/blob/3b5a5536e1652bf39065587347147da1bf44b8fb/beacon_chain/attestation_aggregation.nim#L50-L52
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/attestation_pool.nim#L314
- [x] Data
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/attestation_pool.nim#L328-L333
- [x] Aggregation bits
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/attestation_pool.nim#L289-L292
- [x] Aggregate signature
  https://github.com/status-im/nimbus-eth2/blob/dba39c54d9bb3ded5f624ce026345c3a72f658dd/beacon_chain/attestation_pool.nim#L337-L341
- [x] Broadcast aggregate
  https://github.com/status-im/nimbus-eth2/blob/3b5a5536e1652bf39065587347147da1bf44b8fb/beacon_chain/validator_duties.nim#L604
- [x] `AggregateAndProof`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L424-L425
- [x] `SignedAggregateAndProof`
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L430-L431
- [x] Phase 0 attestation subnet stability
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/beacon_node.nim#L339-L340
- [x] How to avoid slashing
- [x] Proposer slashing
  https://github.com/status-im/nimbus-eth2/blob/devel/beacon_chain/validator_slashing_protection.nim
- [x] Attester slashing
  https://github.com/status-im/nimbus-eth2/blob/devel/beacon_chain/validator_slashing_protection.nim

**Comment by tersec** [comment]
https://github.com/status-im/nimbus-eth2/issues/1868 tracks the actually not-yet-done ones.
