### ISSUE TITLE
Phase 0 validator and p2p-interface implementation tracking

### ISSUE THREAD

**Issue by tersec** [status-im/nimbus-eth2#1868]
This issue starts out only with the not-yet-completed remnants, to avoid useless noise. https://github.com/status-im/nimbus-eth2/issues/1865 and https://github.com/status-im/nimbus-eth2/issues/1869 show the rest.

Required items; some already done:

- [ ] In "Attesting", "A validator should create and broadcast the `attestation` to the associated attestation subnet when either (a) the validator has received a valid block from the expected block proposer for the assigned `slot` or (b) one-third of the `slot` has transpired (`SECONDS_PER_SLOT / 3` seconds after the start of `slot`) -- whichever comes _first_."  Specifically, the "whichever comes _first_" portion. https://github.com/status-im/nimbus-eth2/issues/1700 tracks this. https://github.com/ethereum/eth2.0-specs/pull/2101 updates/tweaks exactly how this would work, so should be considered at the same time.

- [x] An updated, or at least verified-to-be-current, version of `get_eth1_vote()`. https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/mainchain_monitor.nim#L421-L422 is from v0.11.1 still.

  Implemented in https://github.com/status-im/nimbus-eth2/pull/1880

- [x] "Gossipsub domain" requires support for Gossipsub 1.1, while it's still behind a compile-time flag, defaulting to disabled:
https://github.com/status-im/nimbus-eth2/blob/db70f066bab9e5ebde68ae6224f30d77f49eb573/beacon_chain/eth2_network.nim#L29-L32

  https://github.com/status-im/nimbus-eth2/pull/1917 implements this.

- [ ]  https://github.com/ethereum/eth2.0-specs/blob/v1.0.0-rc.0/specs/phase0/p2p-interface.md#topics-and-messages: "clients MUST NOT emit or propagate messages larger than [`GOSSIP_MAX_SIZE`]."

Some optional-for-now (not blocking this issue), but remaining items to track separately:
- [ ] "To maximize profit, the validator should attempt to gather aggregate attestations that include singular attestations from the largest number of validators whose signatures from the same epoch have not previously been added on chain."

- [x] https://github.com/ethereum/eth2.0-specs/blob/v1.0.0-rc.0/specs/phase0/validator.md#deposits -- there this would presumably involve getting deposits from mainchain monitor. They don't come from the Eth2 beacon chain itself.

- [x] https://github.com/ethereum/eth2.0-specs/blob/v1.0.0-rc.0/specs/phase0/validator.md#submit-deposit
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/beacon_node.nim#L1249-L1253

- [ ] We don't initiate slashing ourselves, either attester or proposer.

**Comment by tersec** [comment]
Closing in favor of specific issue(s) for relevant specific items.
