### ISSUE TITLE
Phase 0 P2P Interface Implementation Tracking

### ISSUE THREAD

**Issue by tersec** [status-im/nimbus-eth2#1869]
- `beacon_block` uses a full slot, rather than `MAXIMUM_GOSSIP_CLOCK_DISPARITY` of 0.5 seconds leniency

Items automatically generated from https://raw.githubusercontent.com/ethereum/eth2.0-specs/v1.0.0-rc.0/specs/phase0/p2p-interface.md

- [x] Transport
  https://github.com/status-im/nim-libp2p
- [x] Encryption and identification
- [x] Protocol Negotiation
- [x] Multiplexing
- [x] Configuration
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/spec/network.nim#L25-L29
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/sync_protocol.nim#L11-L12
  https://github.com/status-im/nimbus-eth2/blob/23bec993414df904e9d7ea9d26e65005b981aee0/beacon_chain/spec/datatypes.nim#L68-L69
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/attestation_aggregation.nim#L23
  We only send snappy-compressed messages, so don't need `MESSAGE_DOMAIN_INVALID_SNAPPY`.
  https://github.com/status-im/nimbus-eth2/blob/9810a31447cc23223c34aa5f7ef2be67591d85a5/beacon_chain/eth2_network.nim#L1365-L1368
- [x] MetaData
  https://github.com/status-im/nimbus-eth2/blob/4b38619c4f51847fc591e85327ed226ad46d24ac/beacon_chain/eth2_network.nim#L77-L79
- [ ] The gossip domain: gossipsub
  https://github.com/status-im/nim-libp2p supports Gossipsub 1.0 and 1.1 and is used by https://github.com/status-im/nimbus-eth2/blob/devel/beacon_chain/eth2_network.nim.
- [x] Topics and messages
  For topics:
  https://github.com/status-im/nimbus-eth2/blob/db70f066bab9e5ebde68ae6224f30d77f49eb573/beacon_chain/spec/network.nim#L14-L20
  https://github.com/status-im/nimbus-eth2/blob/db70f066bab9e5ebde68ae6224f30d77f49eb573/beacon_chain/spec/network.nim#L87-L88
  For rejecting messages larger than `GOSSIP_MAX_SIZE`:
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1378
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1406
  Regarding "Clients MUST reject (fail validation) messages containing an incorrect type, or invalid payload.", that happens by construction.
  For message IDs:
  https://github.com/status-im/nimbus-eth2/blob/9810a31447cc23223c34aa5f7ef2be67591d85a5/beacon_chain/eth2_network.nim#L1369-L1373
- [ ] `beacon_block`
- [x] `beacon_aggregate_and_proof`
- [x] `voluntary_exit`
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/exit_pool.nim#L143-L144
- [x] `proposer_slashing`
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/exit_pool.nim#L113-L114
- [x] `attester_slashing`
  https://github.com/status-im/nimbus-eth2/blob/4b38619c4f51847fc591e85327ed226ad46d24ac/beacon_chain/exit_pool.nim#L72-L73
- [x] Attestation subnets
  https://github.com/status-im/nimbus-eth2/blob/db70f066bab9e5ebde68ae6224f30d77f49eb573/beacon_chain/validator_duties.nim#L136-L142
- [x] `beacon_attestation_{subnet_id}`
- [x] Attestations and Aggregation
  https://github.com/status-im/nimbus-eth2/blob/db70f066bab9e5ebde68ae6224f30d77f49eb573/beacon_chain/validator_duties.nim#L136-L142
  https://github.com/status-im/nimbus-eth2/blob/db70f066bab9e5ebde68ae6224f30d77f49eb573/beacon_chain/validator_duties.nim#L503
- [x] Encodings
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L291
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1378
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1388
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1394
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1406
- [x] Protocol identification
- [x] Req/Resp interaction
  "We use ONE stream PER request/response interaction.":
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L119-L122
  and for single/multiple chunks:
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L540-L553
  as regards MAX_CHUNK_SIZE:
  https://github.com/status-im/nimbus-eth2/blob/4b38619c4f51847fc591e85327ed226ad46d24ac/beacon_chain/libp2p_streams_backend.nim#L110-L113
- [x] Requesting side
- [x] Responding side
- [x] Encoding strategies
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L291
- [x] SSZ-snappy encoding strategy
  This is both the SSZ and snappy parts, relatively separate from each other.

  For encoding:
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1431-L1434

  For decoding:
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1405-L1411
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/eth2_network.nim#L1377-L1383

  For the SSZ decoding parts, the SSZ decoding creates sub-decoders bound to specific slices of the overall (snappy-decoded) inputs based on either fixed-size limits or the declared variable-size data type sizes, so by construction can't advance beyond the required SSZ bounds.
- [x] Status
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/sync_protocol.nim#L116
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/sync_protocol.nim#L218
- [x] Goodbye
  https://github.com/status-im/nimbus-eth2/blob/db70f066bab9e5ebde68ae6224f30d77f49eb573/beacon_chain/eth2_network.nim#L169-L177
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/sync_protocol.nim#L186-L189
- [x] BeaconBlocksByRange
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/sync_protocol.nim#L133
- [x] BeaconBlocksByRoot
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/sync_protocol.nim#L164
- [x] Ping
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/sync_protocol.nim#L125-L127
- [x] GetMetaData
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/sync_protocol.nim#L129-L131
- [x] The discovery domain: discv5
- [x] Integration into libp2p stacks
- [x] ENR structure
- [x] Attestation subnet bitfield
  https://github.com/status-im/nimbus-eth2/blob/c5a58555efdef09cd18d2d68b62316fedced156e/beacon_chain/eth2_network.nim#L82-L84
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/beacon_node.nim#L336-L337
  https://github.com/status-im/nimbus-eth2/blob/180bad3a331b7a28e42525fb778f73c761b46906/beacon_chain/beacon_node.nim#L380-L381
- [x] `eth2` field
  https://github.com/status-im/nimbus-eth2/blob/4b38619c4f51847fc591e85327ed226ad46d24ac/beacon_chain/eth2_network.nim#L81-L84

**Comment by tersec** [comment]
Extracted the relevant bits determining what remains to be done for https://github.com/status-im/nimbus-eth2/issues/1868
