### ISSUE TITLE
CI/CD improvements roadmap

### ISSUE THREAD

**Issue by zah** [status-im/nimbus-eth2#485]
#### Start testing the network sim

This can be developed as a custom simulation runner (written in Nim) that tails the json log output produced by the launched beacon nodes and verifies that certain expected events happen (e.g. finalization, participation from all validators, database writes, etc). 

- [x] Implement the simulation runner.

- [x] Define this as a separate CI job to speed up execution and to deal more easily with any potential non-deterministic failures.

#### Create a framework for continuous performance testing

This will allow us to keep track of key performance metrics over time (similar to  https://arewefastyet.com).

- [x] Create benchmark tests/scripts for local use.

- [x] Migrate the existing CI recipes to Jenkins.

- [x] Set up the Jenkins [performance plugin](https://www.blazemeter.com/blog/how-to-use-the-jenkins-performance-plugin/).

- [ ] Make ncli a drop-in replacement of zcli?

#### Increase the variety of the tested hardware

- [x] Set up cross-compiled builds for ARM.

- [x] Set up test runners on variety of target hardware.

- [x] Refactor the test scripts to exploit parallel execution whenever possible (potentially on multiple test runners).

#### Add WASM testing

One of our long-term goals is to ship a competitive set of Ethereum wasm libraries that will be usable by web developers and smart contract developers. To achieve this, our builds need to be light-weight and efficient which is well-aligned with our goals to target resource-restricted devices. Our tight control over the entire build toolkit and our relative lack of third-party dependencies put us in a good position to dominate this space.

- [ ] Set up automated wasm builds

We'll need to track execution times in multiple wasm run-times. The EF research team is currently evaluating the possible ways to execute wasm and they recommend the use of interpreters in initial implementations (the given rationale is that this will save us development time). We can follow their recommendations, but it would be nice to be able to compare the different approaches on our own:
    
- [ ] [wasmi by Parity](https://github.com/paritytech/wasmi)
  Uses an interpreter.

- [ ] [wasmtime by Mozilla](https://wasmtime.dev/) 
  Uses JIT compilation.

- [ ] [lucet by Fastly](https://github.com/fastly/lucet/)
  Uses ahead-of-time compilation.

- [ ] [Innative](https://innative.dev/)
  This is a more experimental LLVM-based ahead-of-time compiler that allows you to control various aspect of the compilation. One of the interesting capabilities is to turn off the memory bounds checking inherent for wasm. Theoretically, the fastest way to execute wasm code for a long-lasting execution environment might be to compile it in this unsafe mode and then to execute it in a hypervisor taking advantage of hardware virtualization to achieve the required sandboxing.

#### Track performance and code size for all stand-alone components

With the WASM goals outlined above, we'll need to develop benchmarks and test cases for the individual components that can act as stand-alone libraries in the future:

Track performance and code size:

- [ ] SSZ reading/writing
- [ ] SSZ hashing
- [ ] SSZ merkle proof verification
- [ ] BLS verification
- [ ] BLS signing
- [ ] Beacon node state transition

Code size only:

- [ ] LibP2P GossipSub chat
- [ ] LibP2P over web-socket (wasm only)
- [ ] Full browser node (wasm only)

Depends on:
* [Create a framework for continuous performance testing](#Create-a-framework-for-continuous-performance-testing)
* [WASM Testing](#Add-WASM-testing)

#### Add code coverage reports

- [ ] Select a code coverage reporting system
   This should be easy to integrate with the CI and preferably easy to install and use locally.
  
- [ ] Create and document an easy-to-use setup for tracking code coverage in Nim programs

#### Detect memory corruptions

This can be implemented as a separate CI run under a memory testing tool such as:

- [ ] Valgrind
- [ ] Address Sanitizer

#### Continuous fuzzing

Our fuzzing effort is tracked in more detail in the [Fuzzing roadmap](). After gaining more experience with fuzzing, we need to evaluate the CI costs for enabling continuous fuzzing. Depending on the obtained results, we need to set up automated tests either on each commit or on a fixed-interval schedule.

- [ ] Create a daily/weekly job for running fuzzing tests
- [ ] Explore a possible partnership with [OSS-Fuzz](https://google.github.io/oss-fuzz/)

#### Continuous delivery for testnets

As our testnets mature, we should automate their deployment in order to more quickly detect potentially introduced regressions (through [alerts]()).

- [ ] Automatically push to docker on each successful build

- [ ] Automatically restart the testnet on each docker push

- [ ] Control the testnet restart with a `testnetGeneration` number in beacon_chain/version.nim. This will allow us to have longer-lived testnets, potentially with nodes having different build versions.

- [ ] Generate docker images for ProtoLambda's Muskoka project.

- [ ] Generate docker images for testing by WhiteBlock?

#### Add linters

- [ ] Treat warnings as errors?

- [ ] Evaluate existing C++ static analyzers and linters for usage with Nim

**Comment by stefantalpalaru** [comment]
> Treat warnings as errors?

Not a good idea, because new compiler versions introduce new warnings.

**Comment by tersec** [comment]
> > Treat warnings as errors?
> 
> Not a good idea, because new compiler versions introduce new warnings.

Good thing introduction of new compiler versions is controlled manually, then.

**Comment by stefantalpalaru** [comment]
I was talking about the C compiler.

**Comment by zah** [comment]
This is issue is still useful as a source of ideas for new developments, but it does not reflect our current roadmap.
